## Spearman's rank correlation for Latin between Self-Similarities and gold standard for graded task

In [1]:
import csv 
import pandas as pd
import numpy as np
from scipy import stats

Reading corpora from csv files

In [2]:
selfsim_ise1 = pd.read_csv('self_sim_by_layer_ISE1.csv', delimiter=',').drop(['instances'], axis=1)

In [3]:
selfsim_ise2 = pd.read_csv('self_sim_by_layer_ISE2.csv', delimiter=',').drop(['instances'], axis=1)

In [4]:
selfsim_ise1.head()

,word,1,2,3,4,5,6,7,8,9,10,11,12
0,credo,0.911239,0.890187,0.868195,0.858112,0.832529,0.812822,0.811099,0.792844,0.802818,0.791391,0.768484,0.709400
1,virtus,0.853860,0.849120,0.830090,0.831719,0.818082,0.777857,0.774065,0.770175,0.788582,0.794453,0.744757,0.750067
2,salus,0.847061,0.835808,0.813430,0.817187,0.810324,0.786888,0.784174,0.775622,0.797745,0.804519,0.759983,0.765689
3,consul,0.910307,0.888482,0.864848,0.847339,0.828357,0.800825,0.793957,0.791107,0.804972,0.830793,0.821337,0.766356
4,hostis,0.878028,0.884818,0.863559,0.869190,0.857252,0.833382,0.807957,0.796528,0.818132,0.822134,0.780174,0.806656

Self-similarities by layer for a specific word from DTA corpus

In [5]:
selfsim_ise1.loc[selfsim_ise1['word'] == 'credo']

,word,1,2,3,4,5,6,7,8,9,10,11,12
0,credo,0.911239,0.890187,0.868195,0.858112,0.832529,0.812822,0.811099,0.792844,0.802818,0.791391,0.768484,0.7094

Self-similarities by layer for a specific word from BZND corpus

In [6]:
selfsim_ise2.loc[selfsim_ise2['word'] == 'credo']

,word,1,2,3,4,5,6,7,8,9,10,11,12
17,credo,0.908242,0.886388,0.864945,0.852445,0.823757,0.802737,0.80103,0.78319,0.794621,0.782763,0.758605,0.693534

In [7]:
def get_substraction_abs(w):
    
    # x1 stores self-similarities from 12 layers for a word w in DTA corpus
    x1 = np.array(selfsim_ise1.loc[selfsim_ise1['word'] == w].drop(['word'], axis=1).values[0])
    # x2 stores self-similarities from 12 layers for a word w in BZND corpus
    x2 = np.array(selfsim_ise2.loc[selfsim_ise2['word'] == w].drop(['word'], axis=1).values[0])
    
    # abs substraction between two rows
    return np.absolute(x1-x2)

In [8]:
get_substraction_abs('credo')

array([0.00299653, 0.00379879, 0.00324961, 0.00566659, 0.0087713 ,
       0.0100847 , 0.01006929, 0.00965424, 0.0081976 , 0.00862796,
       0.00987919, 0.01586582])

In [9]:
rows = [] # rows will store 

for word in list(selfsim_ise1['word']): 
    row = []
    row.append(word)
    row.extend(list(get_substraction_abs(word)))
    rows.append(row)

In [10]:
head = ['word',1,2,3,4,5,6,7,8,9,10,11,12]

In [11]:
with open('self_sim_by_layer_abs.csv', 'w', newline='') as csvfile: # output path
    writer = csv.writer(csvfile, delimiter=',')
    writer.writerow(head)
    for row in rows:
        writer.writerow(row)

## Calculating Spearman's correlation between Self-Similarities from 12 layers and golden standard for graded task

In [12]:
golden = pd.read_csv('graded.tsv', delimiter='\t')

In [13]:
golden = golden.sort_values('word')

In [14]:
golden

           word  change_graded
0       acerbus       0.169367
1        adsumo       0.342616
2       ancilla       0.000000
3        beatus       0.816392
4       civitas       0.322392
5        cohors       0.280830
6     consilium       0.102932
7        consul       0.129886
8         credo       0.370992
9         dolus       0.176682
10       dubius       0.337623
11          dux       0.289054
12      fidelis       0.170439
13        honor       0.290373
14       hostis       0.000000
15    humanitas       0.455671
16    imperator       0.846816
17        itero       0.039678
18          jus       0.350099
19        licet       0.506818
20  necessarius       0.095190
21        nepos       0.364883
22    nobilitas       0.181606
23      oportet       0.102492
24        poena       0.230906
25     pontifex       0.905600
26     potestas       0.548475
27       regnum       0.355575
28  sacramentum       0.688040
29        salus       0.469503
30      sanctus       0.425203
31    sapientia       0.234681
32    scriptura       0.516652
33      senatus       0.264773
34       sensus       0.393510
35      simplex       0.009540
36      templum       0.370184
37      titulus       0.619797
38       virtus       0.397110
39     voluntas       0.144737

In [15]:
self_sim_sumbstracted = pd.read_csv('self_sim_by_layer_abs.csv', delimiter=',')

In [16]:
self_sim_sumbstracted = self_sim_sumbstracted.sort_values('word')

In [17]:
for w1,w2 in zip(self_sim_sumbstracted['word'],golden['word']):
    print(f'{w1}:{w2}')

acerbus:acerbus
adsumo:adsumo
ancilla:ancilla
beatus:beatus
civitas:civitas
cohors:cohors
consilium:consilium
consul:consul
credo:credo
dolus:dolus
dubius:dubius
dux:dux
fidelis:fidelis
honor:honor
hostis:hostis
humanitas:humanitas
imperator:imperator
itero:itero
jus:jus
licet:licet
necessarius:necessarius
nepos:nepos
nobilitas:nobilitas
oportet:oportet
poena:poena
pontifex:pontifex
potestas:potestas
regnum:regnum
sacramentum:sacramentum
salus:salus
sanctus:sanctus
sapientia:sapientia
scriptura:scriptura
senatus:senatus
sensus:sensus
simplex:simplex
templum:templum
titulus:titulus
virtus:virtus
voluntas:voluntas

In [18]:
golden = np.array(golden.drop(['word'], axis=1))

In [19]:
golden = list(golden.flatten())

In [20]:
self_sim_sumbstracted['golden'] = golden

In [21]:
self_sim_sumbstracted

,word,1,2,3,4,5,6,7,8,9,10,11,12,golden
20,acerbus,0.004089,0.004875,0.007504,0.004157,0.002446,0.000507,0.001772,0.004057,0.001779,0.001483,0.003116,0.010823,0.169367
36,adsumo,0.003103,0.005267,0.002909,0.008449,0.012729,0.014625,0.020042,0.024075,0.029379,0.035259,0.037137,0.039751,0.342616
33,ancilla,0.018578,0.018695,0.027373,0.033104,0.041755,0.046438,0.061126,0.061459,0.055241,0.060693,0.068854,0.060816,0.000000
23,beatus,0.000773,0.006014,0.010343,0.014270,0.021656,0.031943,0.029838,0.047785,0.061625,0.068244,0.063214,0.046782,0.816392
11,civitas,0.000744,0.000236,0.003714,0.006889,0.015565,0.021009,0.024920,0.029046,0.025454,0.020850,0.014842,0.030137,0.322392
15,cohors,0.002347,0.002062,0.005314,0.009151,0.006950,0.005535,0.002905,0.002552,0.004539,0.006820,0.006713,0.017268,0.280830
9,consilium,0.001589,0.002229,0.003050,0.005560,0.008314,0.009765,0.008217,0.009359,0.011733,0.015777,0.011544,0.017016,0.102932
3,consul,0.000979,0.002463,0.002682,0.007987,0.010379,0.012885,0.013176,0.012029,0.012409,0.014702,0.010149,0.043656,0.129886
0,credo,0.002997,0.003799,0.003250,0.005667,0.008771,0.010085,0.010069,0.009654,0.008198,0.008628,0.009879,0.015866,0.370992
6,dolus,0.004949,0.006574,0.009670,0.006173,0.005457,0.005153,0.008813,0.009380,0.010043,0.014839,0.013381,0.013061,0.176682
13,dubius,0.002085,0.002600,0.002853,0.005842,0.009765,0.010077,0.005296,0.002907,0.003987,0.010119,0.008451,0.013244,0.337623
18,dux,0.001074,0.000425,0.003506,0.008886,0.010937,0.007655,0.010471,0.010985,0.017867,0.017670,0.008731,0.029498,0.289054
35,fidelis,0.000203,0.003437,0.002279,0.008611,0.012933,0.018445,0.017431,0.016310,0.015216,0.013288,0.020663,0.017695,0.170439
5,honor,0.002963,0.005629,0.013587,0.020206,0.021520,0.020781,0.020549,0.016925,0.021634,0.019421,0.015045,0.037577,0.290373
4,hostis,0.000517,0.001200,0.003213,0.006019,0.006678,0.005880,0.004189,0.004246,0.007097,0.009146,0.008927,0.021452,0.000000
32,humanitas,0.006037,0.005410,0.005908,0.000678,0.000367,0.004374,0.003217,0.001644,0.001744,0.003705,0.001234,0.015823,0.455671
10,imperator,0.029680,0.021471,0.025706,0.019861,0.002967,0.016685,0.008327,0.002138,0.014889,0.032811,0.012158,0.021583,0.846816
39,itero,0.000957,0.003766,0.008504,0.008886,0.010587,0.010359,0.012485,0.009902,0.011400,0.008524,0.011743,0.012851,0.039678
22,jus,0.000234,0.000272,0.004135,0.011625,0.016080,0.014944,0.015453,0.021871,0.025655,0.030713,0.031407,0.024766,0.350099
16,licet,0.001292,0.000932,0.000334,0.001879,0.000894,0.002485,0.004246,0.009338,0.020751,0.027079,0.027932,0.018611,0.506818
19,necessarius,0.002251,0.001276,0.002531,0.000811,0.006366,0.007494,0.006304,0.007023,0.007007,0.004742,0.006366,0.003544,0.095190
26,nepos,0.004343,0.004378,0.003308,0.003249,0.012067,0.020418,0.024004,0.025008,0.029830,0.034859,0.045437,0.042127,0.364883
27,nobilitas,0.002002,0.001610,0.001368,0.001531,0.004073,0.005852,0.003968,0.001223,0.001675,0.001703,0.001585,0.008879,0.181606
17,oportet,0.002205,0.003311,0.002148,0.000243,0.002239,0.004849,0.010585,0.012657,0.011211,0.011147,0.012179,0.012543,0.102492
34,poena,0.002634,0.002389,0.001457,0.006476,0.006934,0.009267,0.008048,0.007351,0.008831,0.009681,0.009787,0.016112,0.230906
24,pontifex,0.003132,0.004503,0.002653,0.000057,0.002775,0.007115,0.009702,0.009698,0.010120,0.002622,0.006597,0.007962,0.905600
8,potestas,0.000134,0.001371,0.005698,0.012350,0.014096,0.013148,0.009671,0.008326,0.007306,0.009156,0.005831,0.012799,0.548475
25,regnum,0.002001,0.000694,0.008597,0.011731,0.016246,0.019398,0.020775,0.022328,0.026983,0.027296,0.028772,0.034737,0.355575
29,sacramentum,0.003497,0.002203,0.001828,0.010935,0.012947,0.021916,0.022265,0.015583,0.017164,0.015351,0.020109,0.025790,0.688040
2,salus,0.002876,0.003689,0.002576,0.002112,0.005256,0.000939,0.002722,0.004743,0.001477,0.000194,0.004824,0.012470,0.469503
37,sanctus,0.000302,0.003986,0.000707,0.018478,0.016870,0.030135,0.024746,0.023062,0.015783,0.006947,0.006822,0.008880,0.425203
31,sapientia,0.002305,0.001734,0.002104,0.007206,0.013050,0.017316,0.015042,0.016584,0.014795,0.012929,0.010905,0.010480,0.234681
38,scriptura,0.011114,0.012596,0.011131,0.003303,0.003562,0.005999,0.008207,0.010417,0.011545,0.014853,0.008698,0.009896,0.516652
12,senatus,0.001616,0.003445,0.004622,0.002942,0.000349,0.000722,0.001847,0.002662,0.000424,0.002354,0.002529,0.016075,0.264773
28,sensus,0.000519,0.000189,0.000959,0.000071,0.000032,0.003115,0.003704,0.008038,0.010573,0.014382,0.016957,0.021851,0.393510
21,simplex,0.004610,0.006527,0.011821,0.016251,0.015938,0.015961,0.014417,0.012741,0.011615,0.014782,0.016167,0.014236,0.009540
14,templum,0.002919,0.002984,0.001763,0.000165,0.002928,0.005311,0.000206,0.000744,0.001808,0.001727,0.003321,0.013498,0.370184
7,titulus,0.004291,0.000269,0.001551,0.011599,0.027813,0.031691,0.037993,0.041923,0.045234,0.043139,0.045686,0.041340,0.619797
1,virtus,0.002764,0.003511,0.005551,0.004137,0.001056,0.000149,0.000994,0.000016,0.000551,0.000300,0.003977,0.013520,0.397110
30,voluntas,0.003047,0.002042,0.002797,0.003523,0.008630,0.010116,0.010349,0.006616,0.002050,0.001290,0.003547,0.005336,0.144737

In [22]:
stats.spearmanr(golden, list(self_sim_sumbstracted['3']))

SpearmanrResult(correlation=-0.08649561433597279, pvalue=0.5956295871424422)

In [23]:
def get_spearman_by_layer(golden_labels):
    rows = []
    for i in range(1,13):
        ssi = self_sim_sumbstracted[str(i)]
        my_cor = stats.spearmanr(golden_labels,ssi)
        rows.append([i, my_cor.correlation, my_cor.pvalue])
    return rows

In [24]:
rows = get_spearman_by_layer(golden)

In [25]:
rows

[[1, 0.12589708724389967, 0.43888243959497875],
 [2, 0.052816736302768647, 0.7461834023243854],
 [3, -0.08649561433597279, 0.5956295871424422],
 [4, -0.014541019763639678, 0.929039097312775],
 [5, -0.054223931763766026, 0.7396535398465283],
 [6, 0.07964726309245218, 0.6251691723704361],
 [7, 0.021952249191559258, 0.8930453770690372],
 [8, 0.021201744945693983, 0.8966819094401907],
 [9, 0.14531638460566362, 0.3709580680514446],
 [10, 0.14409681520613257, 0.3750295149420654],
 [11, 0.04005816412305899, 0.8061352940729338],
 [12, 0.09475116104049082, 0.5608581023188711]]

In [26]:
header = ['layer', 'correlation', 'pvalue']

In [27]:
with open('spearman_latin.csv', 'w', newline='') as csvfile: # output path
    writer = csv.writer(csvfile, delimiter=',')
    writer.writerow(header)
    for row in rows:
        writer.writerow(row)

In [28]:
spearman_ranked = pd.read_csv('spearman_latin.csv', delimiter=',')

### Result: correlation of self-similarities by layer

In [29]:
spearman_ranked

    layer  correlation    pvalue
0       1     0.125897  0.438882
1       2     0.052817  0.746183
2       3    -0.086496  0.595630
3       4    -0.014541  0.929039
4       5    -0.054224  0.739654
5       6     0.079647  0.625169
6       7     0.021952  0.893045
7       8     0.021202  0.896682
8       9     0.145316  0.370958
9      10     0.144097  0.375030
10     11     0.040058  0.806135
11     12     0.094751  0.560858

### Correlation for summed embeddings

In [30]:
selfsim_summed_ise1 = pd.read_csv('self_sim_summed_LatinISE1.csv', delimiter=',').sort_values('word')

In [31]:
selfsim_summed_ise12 = pd.read_csv('self_sim_summed_LatinISE2.csv', delimiter=',').sort_values('word')

In [32]:
def get_substraction_abs2(w):
    
    x1 = selfsim_summed_ise1.loc[selfsim_summed_ise1.word == w, 'self-sim'].values[0]
    x2 = selfsim_summed_ise12.loc[selfsim_summed_ise12.word == w, 'self-sim'].values[0]
    
    return np.absolute(x1-x2)

In [33]:
selfsim_summed_ise1.head()

       word  instances  self-sim
20  acerbus        148  0.846152
36   adsumo         45  0.835565
33  ancilla         96  0.891895
23   beatus        342  0.829985
11  civitas       1691  0.852423

In [34]:
selfsim_summed_ise12.head()

       word  instances  self-sim
39  acerbus        320  0.846981
37   adsumo        264  0.819919
22  ancilla        464  0.850370
8    beatus       2627  0.802642
14  civitas       5752  0.838618

In [35]:
get_substraction_abs2('acerbus')

0.0008286234304590856

In [36]:
substractions = {}

for word in list(selfsim_summed_ise1['word']):
    substractions[word] = get_substraction_abs2(word)

In [37]:
substractions

{'acerbus': 0.0008286234304590856,
 'adsumo': 0.015645836557359405,
 'ancilla': 0.0415247700791902,
 'beatus': 0.02734298178714667,
 'civitas': 0.01380507296754041,
 'cohors': 0.003822309421332215,
 'consilium': 0.007596528051735052,
 'consul': 0.00704980244296638,
 'credo': 0.0064786744976483845,
 'dolus': 0.005949659239322558,
 'dubius': 0.006007921586975273,
 'dux': 0.006928159073935403,
 'fidelis': 0.010772407793354644,
 'honor': 0.015150345337751059,
 'hostis': 0.00489948581310895,
 'humanitas': 0.00024175187461117353,
 'imperator': 0.01106107111187049,
 'itero': 0.008211021136966368,
 'jus': 0.012787021839748336,
 'licet': 0.005635592880370743,
 'necessarius': 0.0031452078042232268,
 'nepos': 0.01600149755891167,
 'nobilitas': 0.001832793224290974,
 'oportet': 0.005552724701632705,
 'poena': 0.004482071561759726,
 'pontifex': 0.005001773341193783,
 'potestas': 0.008071186708307976,
 'regnum': 0.014113483410196581,
 'sacramentum': 0.01024790253192831,
 'salus': 0.00011971377631336821,
 'sanctus': 0.01000019208191727,
 'sapientia': 0.009390509247040324,
 'scriptura': 0.0009009692035183425,
 'senatus': 0.001457759035543571,
 'sensus': 0.004009321733712379,
 'simplex': 0.011803999471984294,
 'templum': 7.808339852899415e-05,
 'titulus': 0.023740552168792783,
 'virtus': 0.0013989458400300858,
 'voluntas': 0.0032789342766568197}

In [38]:
stats.spearmanr(golden, list(substractions.values()))

SpearmanrResult(correlation=0.04184061170698901, pvalue=0.7976850288606296)